import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased container px-4 md:px-0 mx-auto`}
      >
        <div className="min-h-screen flex flex-col">
          
          {/* Header */}
          <header className="sticky top-0 z-50 bg-white mt-4">
            <Header />
          </header>

          {/* Hauptinhalt */}
          <main className="flex-grow ">
            {children}
          </main>

          {/* Footer immer am Ende */}
          <footer className="mt-auto">
            <Footer />
          </footer>
          
        </div>
      </body>
    </html>
  );
}
